# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf-definitions/arrays/Array3FBuf.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'protobuf-definitions/arrays/Array3FBuf.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,protobuf-definitions/arrays/Array3FBuf.proto\x12\x04\x64sis\"\xf7\x01\n\nArray3FBuf\x12\'\n\x06length\x18\x01 \x01(\x0b\x32\x17.dsis.Array3FBuf.Index3\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02\x12\'\n\x06header\x18\x03 \x01(\x0b\x32\x17.dsis.Array3FBuf.Header\x12,\n\x0bsliceHeader\x18\x04 \x03(\x0b\x32\x17.dsis.Array3FBuf.Header\x1a\x30\n\x06Header\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\x10\n\x08scalarXY\x18\x03 \x01(\x05\x1a)\n\x06Index3\x12\t\n\x01i\x18\x01 \x01(\x05\x12\t\n\x01j\x18\x02 \x01(\x05\x12\t\n\x01k\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf_definitions.arrays.Array3FBuf_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARRAY3FBUF']._serialized_start=55
  _globals['_ARRAY3FBUF']._serialized_end=302
  _globals['_ARRAY3FBUF_HEADER']._serialized_start=211
  _globals['_ARRAY3FBUF_HEADER']._serialized_end=259
  _globals['_ARRAY3FBUF_INDEX3']._serialized_start=261
  _globals['_ARRAY3FBUF_INDEX3']._serialized_end=302
# @@protoc_insertion_point(module_scope)
