# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf-definitions/arrays/Array2FBuf.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'protobuf-definitions/arrays/Array2FBuf.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,protobuf-definitions/arrays/Array2FBuf.proto\x12\x04\x64sis\"\xd1\x01\n\nArray2FBuf\x12\'\n\x06length\x18\x01 \x01(\x0b\x32\x17.dsis.Array2FBuf.Index2\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02\x12\'\n\x06header\x18\x03 \x01(\x0b\x32\x17.dsis.Array2FBuf.Header\x1a\x43\n\x06Header\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\x11\n\tshotpoint\x18\x03 \x01(\x02\x12\x10\n\x08scalarXY\x18\x04 \x01(\x05\x1a\x1e\n\x06Index2\x12\t\n\x01i\x18\x01 \x01(\x05\x12\t\n\x01k\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf_definitions.arrays.Array2FBuf_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARRAY2FBUF']._serialized_start=55
  _globals['_ARRAY2FBUF']._serialized_end=264
  _globals['_ARRAY2FBUF_HEADER']._serialized_start=165
  _globals['_ARRAY2FBUF_HEADER']._serialized_end=232
  _globals['_ARRAY2FBUF_INDEX2']._serialized_start=234
  _globals['_ARRAY2FBUF_INDEX2']._serialized_end=264
# @@protoc_insertion_point(module_scope)
