# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf-definitions/arrays/Array3IBuf.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'protobuf-definitions/arrays/Array3IBuf.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,protobuf-definitions/arrays/Array3IBuf.proto\x12\x04\x64sis\"n\n\nArray3IBuf\x12\'\n\x06length\x18\x01 \x01(\x0b\x32\x17.dsis.Array3IBuf.Index3\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x11\x1a)\n\x06Index3\x12\t\n\x01i\x18\x01 \x01(\x05\x12\t\n\x01j\x18\x02 \x01(\x05\x12\t\n\x01k\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf_definitions.arrays.Array3IBuf_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARRAY3IBUF']._serialized_start=54
  _globals['_ARRAY3IBUF']._serialized_end=164
  _globals['_ARRAY3IBUF_INDEX3']._serialized_start=123
  _globals['_ARRAY3IBUF_INDEX3']._serialized_end=164
# @@protoc_insertion_point(module_scope)
