# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf-definitions/arrays/Array3FBufList.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'protobuf-definitions/arrays/Array3FBufList.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0protobuf-definitions/arrays/Array3FBufList.proto\x12\x04\x64sis\"\xe9\x02\n\x0e\x41rray3FBufList\x12\x30\n\x07\x61rray3F\x18\x01 \x03(\x0b\x32\x1f.dsis.Array3FBufList.Array3FBuf\x1a\xa4\x02\n\nArray3FBuf\x12\x36\n\x06length\x18\x01 \x01(\x0b\x32&.dsis.Array3FBufList.Array3FBuf.Index3\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02\x12\x36\n\x06header\x18\x03 \x01(\x0b\x32&.dsis.Array3FBufList.Array3FBuf.Header\x12;\n\x0bsliceHeader\x18\x04 \x03(\x0b\x32&.dsis.Array3FBufList.Array3FBuf.Header\x1a\x30\n\x06Header\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\x10\n\x08scalarXY\x18\x03 \x01(\x05\x1a)\n\x06Index3\x12\t\n\x01i\x18\x01 \x01(\x05\x12\t\n\x01j\x18\x02 \x01(\x05\x12\t\n\x01k\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf_definitions.arrays.Array3FBufList_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARRAY3FBUFLIST']._serialized_start=59
  _globals['_ARRAY3FBUFLIST']._serialized_end=420
  _globals['_ARRAY3FBUFLIST_ARRAY3FBUF']._serialized_start=128
  _globals['_ARRAY3FBUFLIST_ARRAY3FBUF']._serialized_end=420
  _globals['_ARRAY3FBUFLIST_ARRAY3FBUF_HEADER']._serialized_start=329
  _globals['_ARRAY3FBUFLIST_ARRAY3FBUF_HEADER']._serialized_end=377
  _globals['_ARRAY3FBUFLIST_ARRAY3FBUF_INDEX3']._serialized_start=379
  _globals['_ARRAY3FBUFLIST_ARRAY3FBUF_INDEX3']._serialized_end=420
# @@protoc_insertion_point(module_scope)
