# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf-definitions/geometry/FaultPlane.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'protobuf-definitions/geometry/FaultPlane.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.protobuf-definitions/geometry/FaultPlane.proto\x12\x04\x64sis\"\x95\x01\n\nFaultPlane\x12\x33\n\x0c\x66\x61ultSegment\x18\x01 \x03(\x0b\x32\x1d.dsis.FaultPlane.FaultSegment\x1aR\n\x0c\x46\x61ultSegment\x12\t\n\x01x\x18\x01 \x03(\x01\x12\t\n\x01y\x18\x02 \x03(\x01\x12\t\n\x01z\x18\x03 \x03(\x01\x12\x0f\n\x07line_no\x18\x04 \x03(\x01\x12\x10\n\x08trace_no\x18\x05 \x03(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf_definitions.geometry.FaultPlane_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FAULTPLANE']._serialized_start=57
  _globals['_FAULTPLANE']._serialized_end=206
  _globals['_FAULTPLANE_FAULTSEGMENT']._serialized_start=124
  _globals['_FAULTPLANE_FAULTSEGMENT']._serialized_end=206
# @@protoc_insertion_point(module_scope)
