# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf-definitions/horizon/HorizonData3D.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'protobuf-definitions/horizon/HorizonData3D.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0protobuf-definitions/horizon/HorizonData3D.proto\x12\x04\x64sis\"\xe7\x03\n\rHorizonData3D\x12&\n\x04mode\x18\x01 \x01(\x0e\x32\x18.dsis.HorizonData3D.MODE\x12\x15\n\rfirstRowIndex\x18\x02 \x01(\x05\x12\x14\n\x0cnumberOfRows\x18\x03 \x01(\x05\x12\x18\n\x10\x66irstColumnIndex\x18\x04 \x01(\x05\x12\x17\n\x0fnumberOfColumns\x18\x05 \x01(\x05\x12+\n\x05lines\x18\x06 \x03(\x0b\x32\x18.dsis.HorizonData3D.LineB\x02\x10\x00\x12,\n\x07samples\x18\x07 \x01(\x0b\x32\x1b.dsis.HorizonData3D.Samples\x1a\x86\x01\n\x04Line\x12\x35\n\tdirection\x18\x01 \x02(\x0e\x32\".dsis.HorizonData3D.Line.DIRECTION\x12\x11\n\tlineIndex\x18\x02 \x02(\x05\x12\x12\n\x06values\x18\x03 \x03(\x02\x42\x02\x10\x00\" \n\tDIRECTION\x12\x07\n\x03ROW\x10\x01\x12\n\n\x06\x43OLUMN\x10\x02\x1aK\n\x07Samples\x12\x17\n\x0b\x63olumnIndex\x18\x01 \x03(\x05\x42\x02\x10\x00\x12\x14\n\x08rowIndex\x18\x02 \x03(\x05\x42\x02\x10\x00\x12\x11\n\x05value\x18\x03 \x03(\x02\x42\x02\x10\x00\"\x1d\n\x04MODE\x12\x08\n\x04\x46ULL\x10\x01\x12\x0b\n\x07SAMPLES\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf_definitions.horizon.HorizonData3D_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HORIZONDATA3D_LINE'].fields_by_name['values']._loaded_options = None
  _globals['_HORIZONDATA3D_LINE'].fields_by_name['values']._serialized_options = b'\020\000'
  _globals['_HORIZONDATA3D_SAMPLES'].fields_by_name['columnIndex']._loaded_options = None
  _globals['_HORIZONDATA3D_SAMPLES'].fields_by_name['columnIndex']._serialized_options = b'\020\000'
  _globals['_HORIZONDATA3D_SAMPLES'].fields_by_name['rowIndex']._loaded_options = None
  _globals['_HORIZONDATA3D_SAMPLES'].fields_by_name['rowIndex']._serialized_options = b'\020\000'
  _globals['_HORIZONDATA3D_SAMPLES'].fields_by_name['value']._loaded_options = None
  _globals['_HORIZONDATA3D_SAMPLES'].fields_by_name['value']._serialized_options = b'\020\000'
  _globals['_HORIZONDATA3D'].fields_by_name['lines']._loaded_options = None
  _globals['_HORIZONDATA3D'].fields_by_name['lines']._serialized_options = b'\020\000'
  _globals['_HORIZONDATA3D']._serialized_start=59
  _globals['_HORIZONDATA3D']._serialized_end=546
  _globals['_HORIZONDATA3D_LINE']._serialized_start=304
  _globals['_HORIZONDATA3D_LINE']._serialized_end=438
  _globals['_HORIZONDATA3D_LINE_DIRECTION']._serialized_start=406
  _globals['_HORIZONDATA3D_LINE_DIRECTION']._serialized_end=438
  _globals['_HORIZONDATA3D_SAMPLES']._serialized_start=440
  _globals['_HORIZONDATA3D_SAMPLES']._serialized_end=515
  _globals['_HORIZONDATA3D_MODE']._serialized_start=517
  _globals['_HORIZONDATA3D_MODE']._serialized_end=546
# @@protoc_insertion_point(module_scope)
