# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf-definitions/tabular/PropertyTableSet.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'protobuf-definitions/tabular/PropertyTableSet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3protobuf-definitions/tabular/PropertyTableSet.proto\x12\x04\x64sis\"\x80\x08\n\x10PropertyTableSet\x12;\n\rpropertyTable\x18\x01 \x03(\x0b\x32$.dsis.PropertyTableSet.PropertyTable\x1a\xae\x07\n\rPropertyTable\x12U\n\x13propertySetNameType\x18\x01 \x01(\x0e\x32\x38.dsis.PropertyTableSet.PropertyTable.PropertySetNameType\x12G\n\x0cpropertyInfo\x18\x02 \x03(\x0b\x32\x31.dsis.PropertyTableSet.PropertyTable.PropertyInfo\x1a\x9c\x05\n\x0cPropertyInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rproperty_type\x18\x02 \x01(\t\x12M\n\tdata_type\x18\x03 \x01(\x0e\x32:.dsis.PropertyTableSet.PropertyTable.PropertyInfo.DataType\x12\x14\n\x0c\x64isplay_name\x18\x04 \x01(\t\x12\x0e\n\x06remark\x18\x05 \x01(\t\x12\x11\n\tunit_name\x18\x06 \x01(\t\x12\x11\n\tunit_type\x18\x07 \x01(\t\x12\x19\n\x11property_category\x18\x08 \x01(\t\x12X\n\x0epropertyValues\x18\t \x01(\x0b\x32@.dsis.PropertyTableSet.PropertyTable.PropertyInfo.PropertyValues\x1a\xe9\x01\n\x0ePropertyValues\x12M\n\tdata_type\x18\x01 \x01(\x0e\x32:.dsis.PropertyTableSet.PropertyTable.PropertyInfo.DataType\x12\x13\n\x0b\x64\x61ta_string\x18\x02 \x03(\t\x12\x10\n\x08\x64\x61ta_int\x18\x03 \x03(\x11\x12\x12\n\ndata_float\x18\x04 \x03(\x02\x12\x13\n\x0b\x64\x61ta_double\x18\x05 \x03(\x01\x12\x11\n\tdata_long\x18\x06 \x03(\x12\x12\x12\n\ndata_short\x18\x07 \x03(\x11\x12\x11\n\tdata_byte\x18\x08 \x01(\x0c\"k\n\x08\x44\x61taType\x12\n\n\x06STRUCT\x10\x00\x12\x07\n\x03INT\x10\x01\x12\t\n\x05\x46LOAT\x10\x02\x12\n\n\x06\x44OUBLE\x10\x03\x12\x08\n\x04LONG\x10\x04\x12\n\n\x06STRING\x10\x05\x12\t\n\x05SHORT\x10\x06\x12\x08\n\x04\x42YTE\x10\x07\x12\x08\n\x04\x43HAR\x10\x08\"^\n\x13PropertySetNameType\x12\t\n\x05TRACE\x10\x00\x12\x08\n\x04NODE\x10\x01\x12\x0b\n\x07\x45LEMENT\x10\x02\x12\t\n\x05SLICE\x10\x03\x12\x0c\n\x08\x46RACTURE\x10\x04\x12\x0c\n\x08\x46RAC_NET\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf_definitions.tabular.PropertyTableSet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROPERTYTABLESET']._serialized_start=62
  _globals['_PROPERTYTABLESET']._serialized_end=1086
  _globals['_PROPERTYTABLESET_PROPERTYTABLE']._serialized_start=144
  _globals['_PROPERTYTABLESET_PROPERTYTABLE']._serialized_end=1086
  _globals['_PROPERTYTABLESET_PROPERTYTABLE_PROPERTYINFO']._serialized_start=322
  _globals['_PROPERTYTABLESET_PROPERTYTABLE_PROPERTYINFO']._serialized_end=990
  _globals['_PROPERTYTABLESET_PROPERTYTABLE_PROPERTYINFO_PROPERTYVALUES']._serialized_start=648
  _globals['_PROPERTYTABLESET_PROPERTYTABLE_PROPERTYINFO_PROPERTYVALUES']._serialized_end=881
  _globals['_PROPERTYTABLESET_PROPERTYTABLE_PROPERTYINFO_DATATYPE']._serialized_start=883
  _globals['_PROPERTYTABLESET_PROPERTYTABLE_PROPERTYINFO_DATATYPE']._serialized_end=990
  _globals['_PROPERTYTABLESET_PROPERTYTABLE_PROPERTYSETNAMETYPE']._serialized_start=992
  _globals['_PROPERTYTABLESET_PROPERTYTABLE_PROPERTYSETNAMETYPE']._serialized_end=1086
# @@protoc_insertion_point(module_scope)
