# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf-definitions/seismic/SeismicDataHeader2D.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'protobuf-definitions/seismic/SeismicDataHeader2D.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6protobuf-definitions/seismic/SeismicDataHeader2D.proto\x12\x04\x64sis\"\xb6\x04\n\x13SeismicDataHeader2D\x12\x34\n\x08\x64\x61taType\x18\x01 \x02(\x0e\x32\".dsis.SeismicDataHeader2D.DataType\x12/\n\x05\x66irst\x18\x02 \x02(\x0b\x32 .dsis.SeismicDataHeader2D.Index2\x12\x30\n\x06length\x18\x03 \x02(\x0b\x32 .dsis.SeismicDataHeader2D.Index2\x12\x33\n\tincrement\x18\x04 \x02(\x0b\x32 .dsis.SeismicDataHeader2D.Index2\x12,\n\x04mode\x18\x05 \x02(\x0e\x32\x1e.dsis.SeismicDataHeader2D.Mode\x12\x34\n\rnavigationCRS\x18\x06 \x01(\x0b\x32\x1d.dsis.SeismicDataHeader2D.CRS\x1a(\n\x03\x43RS\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x13\n\x0bisProjected\x18\x02 \x02(\x08\x1a\x1e\n\x06Index2\x12\t\n\x01i\x18\x01 \x02(\x05\x12\t\n\x01k\x18\x02 \x01(\x05\"3\n\x08\x44\x61taType\x12\t\n\x05\x46LOAT\x10\x01\x12\t\n\x05SHORT\x10\x02\x12\x07\n\x03INT\x10\x03\x12\x08\n\x04\x42YTE\x10\x04\"n\n\x04Mode\x12\n\n\x06XSLICE\x10\x01\x12\n\n\x06YSLICE\x10\x02\x12\t\n\x05TRACE\x10\x03\x12\x06\n\x02XY\x10\x04\x12\x06\n\x02YX\x10\x05\x12\r\n\tLIVETRACE\x10\x06\x12\x0b\n\x07XSLICES\x10\x07\x12\x0b\n\x07YSLICES\x10\x08\x12\n\n\x06ZSLICE\x10\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf_definitions.seismic.SeismicDataHeader2D_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEISMICDATAHEADER2D']._serialized_start=65
  _globals['_SEISMICDATAHEADER2D']._serialized_end=631
  _globals['_SEISMICDATAHEADER2D_CRS']._serialized_start=394
  _globals['_SEISMICDATAHEADER2D_CRS']._serialized_end=434
  _globals['_SEISMICDATAHEADER2D_INDEX2']._serialized_start=436
  _globals['_SEISMICDATAHEADER2D_INDEX2']._serialized_end=466
  _globals['_SEISMICDATAHEADER2D_DATATYPE']._serialized_start=468
  _globals['_SEISMICDATAHEADER2D_DATATYPE']._serialized_end=519
  _globals['_SEISMICDATAHEADER2D_MODE']._serialized_start=521
  _globals['_SEISMICDATAHEADER2D_MODE']._serialized_end=631
# @@protoc_insertion_point(module_scope)
