# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf-definitions/seismic/SeismicData.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'protobuf-definitions/seismic/SeismicData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.protobuf-definitions/seismic/SeismicData.proto\x12\x04\x64sis\"\xdd\x01\n\x0bSeismicData\x12(\n\x06length\x18\x01 \x01(\x0b\x32\x18.dsis.SeismicData.Index3\x12$\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x16.dsis.SeismicData.Data\x1aS\n\x04\x44\x61ta\x12\x12\n\ndata_float\x18\x01 \x03(\x02\x12\x12\n\ndata_short\x18\x02 \x03(\x11\x12\x10\n\x08\x64\x61ta_int\x18\x03 \x03(\x11\x12\x11\n\tdata_byte\x18\x04 \x01(\x0c\x1a)\n\x06Index3\x12\t\n\x01i\x18\x01 \x01(\x05\x12\t\n\x01j\x18\x02 \x01(\x05\x12\t\n\x01k\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf_definitions.seismic.SeismicData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEISMICDATA']._serialized_start=57
  _globals['_SEISMICDATA']._serialized_end=278
  _globals['_SEISMICDATA_DATA']._serialized_start=152
  _globals['_SEISMICDATA_DATA']._serialized_end=235
  _globals['_SEISMICDATA_INDEX3']._serialized_start=237
  _globals['_SEISMICDATA_INDEX3']._serialized_end=278
# @@protoc_insertion_point(module_scope)
