name: Test Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-build:
    name: Test package build
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v5
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: x64
    
    - name: Install build dependencies
      run: |
        pip install build twine
    
    - name: Build package
      run: |
        python -m build
    
    - name: Check package with twine
      run: |
        twine check dist/*
    
    - name: List built artifacts
      run: |
        ls -lh dist/
    
    - name: Test installation
      run: |
        pip install dist/*.whl
        python -c "import dsis_model_sdk; print(f'Successfully imported dsis_model_sdk')"
        python -c "from dsis_model_sdk.models.common import Well, Basin; print(f'Successfully imported common models')"
        python -c "from dsis_model_sdk.models.native import Well, Activity; print(f'Successfully imported native models')"

